"""WebResearcher — Step 1: determine topic headings.

Three modes (tried in order):
  1. config   — headings are listed in book_config['web_research']['headings']
  2. discover — headings are extracted from web search results (目次・章構成)
  3. infer    — headings are generated by an LLM given the subject / author

Output: list[Heading]
"""

from __future__ import annotations

import json
import re
import unicodedata
from dataclasses import dataclass

import time

from langchain_ollama import ChatOllama

from cogito.utils import event_log

from cogito.utils.logger import create_step, extract_json
from cogito.services.web_researcher.web_search import search_batch


@dataclass
class Heading:
    id: str         # snake_case slug, e.g. "method_of_doubt"
    title: str      # human-readable, e.g. "Method of Doubt"
    description: str = ""  # optional context for search query generation


# ── Step 0: structure discovery ──────────────────────────────────────────────

# Patterns for Japanese and English chapter markers in search result text
_CHAPTER_PATTERNS = [
    # 第1章 タイトル  /  第１章 タイトル
    # Requires at least one whitespace after 章 to exclude in-text references like 第一章で述べた
    re.compile(
        r"第\s*[0-9０-９一二三四五六七八九十百]+\s*章[\s　]+([^\n第【】「」【】\[\]]{2,60})",
        re.UNICODE,
    ),
    # 序章 / 終章 / おわりに / はじめに / あとがき  (only if chapter patterns also found)
    re.compile(
        r"(序章|終章|はじめに|おわりに|あとがき|プロローグ|エピローグ)\s*[　\s]*([^\n【】「」]{0,40})",
        re.UNICODE,
    ),
    # Chapter 1: Title  (English)
    re.compile(
        r"Chapter\s+(\d+)[:\.\s]+([^\n\[\]]{3,80})",
        re.IGNORECASE,
    ),
]

DESCRIPTION_ENRICH_PROMPT = """\
The following are chapter titles extracted from web search results about the book
"{title}" by {author}.

For each chapter, write a one-sentence English description of what it likely covers
based on the title and any context available.

Chapters:
{chapters_json}

Respond ONLY with valid JSON:
{{
  "chapters": [
    {{"id": "slug", "title": "original title", "description": "one sentence in English"}}
  ]
}}
"""

# ── Step 0 fallback: LLM-only infer prompt ───────────────────────────────────

HEADING_INFER_PROMPT = """\
You are a knowledgeable research assistant.

Given the following subject, list the 8-12 most important themes, chapters, or conceptual
sections that a researcher would need to understand in order to fully grasp the content
and significance of this work. Ensure ALL key terms listed below appear as headings or
are explicitly covered under a heading — do not omit any.

Subject: {subject}
Author: {author}
{key_terms_block}
For each heading provide:
- id: a snake_case slug
- title: the heading name (keep it concise, may include Japanese or original-language terms)
- description: one sentence explaining why this section is important

Respond ONLY with valid JSON:
{{
  "headings": [
    {{"id": "...", "title": "...", "description": "..."}}
  ]
}}
"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _slugify(text) -> str:
    """Convert a title to a snake_case slug."""
    text = str(text)
    text = unicodedata.normalize("NFKC", text.lower())
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s-]+", "_", text.strip())
    return text[:60] or "heading"


def _format_results(raw_results: list[dict], max_chars: int = 8000) -> str:
    """Format search results into a compact text block for LLM consumption."""
    lines: list[str] = []
    total = 0
    for r in raw_results:
        snippet = f"[{r.get('title', '')}]\n{r.get('body', '')[:400]}\n"
        if total + len(snippet) > max_chars:
            break
        lines.append(snippet)
        total += len(snippet)
    return "\n".join(lines)


# ── Step 0: web-driven structure discovery ────────────────────────────────────

_KANJI_DIGIT = {
    "一": 1, "二": 2, "三": 3, "四": 4, "五": 5,
    "六": 6, "七": 7, "八": 8, "九": 9, "十": 10,
}


def _parse_chapter_num(raw: str) -> int | None:
    """Return the Arabic integer chapter number from a 第N章 string, or None."""
    m = re.match(r"第\s*([0-9]+)\s*章", raw)
    if m:
        return int(m.group(1))
    m = re.match(r"第([一二三四五六七八九十]+)章", raw)
    if m:
        return _KANJI_DIGIT.get(m.group(1))
    return None


def _extract_chapters_regex(raw_results: list[dict]) -> list[str]:
    """Extract chapter titles from search result bodies using regex patterns.

    Returns a de-duplicated ordered list of chapter title strings, one per
    chapter number (第N章).  In-text references like 「第一章で述べたように」are
    excluded by requiring whitespace after 章.
    """
    full_text = "\n".join(
        f"{r.get('title', '')}\n{r.get('body', '')}" for r in raw_results
    )
    # Normalize full-width digits/spaces for consistent matching
    full_text = unicodedata.normalize("NFKC", full_text)

    # Primary: 第N章 patterns — deduplicate by chapter number
    # For each chapter number, keep the longest clean core title found.
    by_chapter: dict[int, str] = {}

    for m in _CHAPTER_PATTERNS[0].finditer(full_text):
        raw = m.group(0).replace("\u3000", " ").strip()
        num = _parse_chapter_num(raw)
        if num is None:
            continue

        # Extract the title portion (everything after 章 and its whitespace)
        after = re.sub(r"^第\s*[0-9一二三四五六七八九十百]+\s*章[\s　]+", "", raw).strip()
        # Strip parenthetical sub-items like (勉強とは… ほか). or （…）
        clean = re.sub(r"[（(（].*", "", after).strip().rstrip(".")
        clean_title = f"第{num}章 {clean}".strip() if clean else f"第{num}章"

        existing = by_chapter.get(num, "")
        if not existing or len(clean) > len(existing.split(" ", 1)[-1]):
            by_chapter[num] = clean_title

    found: list[str] = [by_chapter[k] for k in sorted(by_chapter.keys())]

    # Secondary: 序章/終章/はじめに etc. — only if we already found chapters
    if found:
        seen: set[str] = set(found)
        for m in _CHAPTER_PATTERNS[1].finditer(full_text):
            marker = m.group(1).strip()
            subtitle = (m.group(2) or "").strip()
            title = f"{marker}　{subtitle}".strip() if subtitle else marker
            key = re.sub(r"\s+", " ", title)
            if key and key not in seen:
                seen.add(key)
                found.insert(0, key)  # prefix sections go first

    # English chapters if no Japanese found
    if not found:
        seen = set()
        for m in _CHAPTER_PATTERNS[2].finditer(full_text):
            title = f"Chapter {m.group(1)}: {m.group(2).strip()}"
            key = re.sub(r"\s+", " ", title)
            if key and key not in seen:
                seen.add(key)
                found.append(key)

    return found[:20]  # cap at 20


def _is_gemma4(model: str) -> bool:
    return "gemma4" in model.lower()

def discover_structure(
    title: str,
    author: str,
    model: str = "llama3",
) -> tuple[list[Heading], str, list[dict]]:
    """Search the web for the book's table of contents / chapter structure.

    Strategy:
      1. Tavily/DuckDuckGo search with ToC-focused queries
      2. Regex extraction of 第N章 patterns from raw results (no LLM for titles)
      3. LLM enrichment: add short English descriptions to each extracted chapter
      4. Return headings + confidence

    Returns:
        (headings, confidence, log_entries)
        confidence: "high" (regex found chapters) | "low" (none found) | "none"
    """
    log: list[dict] = []

    queries = [
        f'"{title}" {author} 目次',
        f'"{title}" {author} 章 内容',
        f'"{title}" 書評 目次 章',
    ]

    print(f"  [structure discovery] Searching for ToC of '{title}' ...", flush=True)
    raw_results = search_batch(queries, max_results=5)

    if not raw_results:
        log.append(create_step(
            layer="web_researcher", node="planner",
            action="discover_structure",
            input_summary=f"title={title}",
            reasoning="No web results — falling back to LLM inference",
        ))
        return [], "none", log

    # ── Regex extraction ──────────────────────────────────────────────────────
    chapter_titles = _extract_chapters_regex(raw_results)
    confidence = "high" if len(chapter_titles) >= 2 else "low"

    if not chapter_titles:
        print(
            f"  [structure discovery] → no chapters found by regex "
            f"(will fall back to LLM inference)",
            flush=True,
        )
        log.append(create_step(
            layer="web_researcher", node="planner",
            action="discover_structure",
            input_summary=f"{len(raw_results)} results, 0 chapters extracted",
            reasoning="Regex found no chapter patterns — falling back",
        ))
        return [], "none", log

    # ── LLM enrichment: add English descriptions only ────────────────────────
    chapters_input = [{"title": t} for t in chapter_titles]
    enriched: list[dict] = []
    try:
        gemma4 = _is_gemma4(model)
        num_ctx = 8192
        llm = ChatOllama(model=model, temperature=0.1, num_ctx=num_ctx,
                         **({}  if gemma4 else {"format": "json"}))
        prompt = DESCRIPTION_ENRICH_PROMPT.format(
            title=title,
            author=author,
            chapters_json=json.dumps(chapters_input, ensure_ascii=False, indent=2),
        )
        _t0 = time.time()
        raw_resp = llm.invoke(prompt).content
        event_log.llm("web_researcher/planner", "enrich_chapter_descriptions", model, time.time() - _t0)
        parsed_enrich = extract_json(raw_resp)
        enriched = parsed_enrich.get("chapters", [])
    except Exception:
        enriched = [{"title": t, "id": _slugify(t), "description": ""} for t in chapter_titles]

    # Build Heading objects — titles come from regex, descriptions from LLM
    enrich_by_title = {e.get("title", ""): e for e in enriched}
    headings: list[Heading] = []
    for orig_title in chapter_titles:
        e = enrich_by_title.get(orig_title, {})
        slug = _slugify(e.get("id", "") or orig_title)
        headings.append(Heading(
            id=slug,
            title=orig_title,
            description=e.get("description", ""),
        ))

    print(
        f"  [structure discovery] → {len(headings)} headings "
        f"(confidence={confidence}, regex-extracted)",
        flush=True,
    )

    log.append(create_step(
        layer="web_researcher", node="planner",
        action="discover_structure",
        input_summary=f"{len(raw_results)} results → {len(chapter_titles)} chapters by regex",
        parsed_output={"chapters": chapter_titles, "confidence": confidence},
        reasoning=f"Extracted {len(headings)} real chapter titles via regex",
    ))

    return headings, confidence, log


# ── Main entry point ──────────────────────────────────────────────────────────

def plan_headings(
    subject: str,
    author: str = "",
    book_config: dict | None = None,
    model: str = "llama3",
) -> tuple[list[Heading], list[dict]]:
    """Determine which headings to research.

    Priority:
      1. book_config['web_research']['headings']  → use directly (manual/curated)
      2. Web-driven structure discovery            → search for actual ToC
      3. LLM-inferred from subject/author          → fallback

    Args:
        subject:     Full description of the subject.
        author:      Author name.
        book_config: Optional loaded book config dict.
        model:       Ollama model for LLM steps.

    Returns:
        (list[Heading], thinking_log_entries)
    """
    log: list[dict] = []

    # ── 1. Config-defined headings (manual override) ──────────────────────────
    if book_config:
        wr_config = book_config.get("web_research", {})
        raw_headings = wr_config.get("headings", [])
        if raw_headings:
            headings = [
                Heading(
                    id=h["id"],
                    title=h["title"],
                    description=h.get("description", ""),
                )
                for h in raw_headings
            ]
            log.append(create_step(
                layer="web_researcher", node="planner",
                action="use_config_headings",
                input_summary=f"{len(headings)} headings from book config",
                parsed_output={"headings": [h.__dict__ for h in headings]},
                reasoning="Using pre-defined headings from book config (manual override)",
            ))
            return headings, log

    # ── 2. Web-driven structure discovery ─────────────────────────────────────
    # Extract book title from config or subject for targeted queries
    title = subject
    if book_config:
        bk = book_config.get("book", {})
        title = bk.get("title_ja") or bk.get("title") or subject

    discovered, confidence, disc_log = discover_structure(
        title=title, author=author, model=model
    )
    log.extend(disc_log)

    if discovered and confidence in ("high", "medium"):
        log.append(create_step(
            layer="web_researcher", node="planner",
            action="use_discovered_headings",
            input_summary=f"{len(discovered)} headings discovered (confidence={confidence})",
            parsed_output={"headings": [h.__dict__ for h in discovered]},
            reasoning=f"Using web-discovered structure (confidence={confidence})",
        ))
        return discovered, log

    # ── 3. LLM-inferred headings (fallback — no web context) ──────────────────
    gemma4 = _is_gemma4(model)
    num_ctx = 8192 if gemma4 else 16384
    llm = ChatOllama(model=model, temperature=0.2, num_ctx=num_ctx,
                     **({}  if gemma4 else {"format": "json"}))

    key_terms = (book_config or {}).get("context", {}).get("key_terms", [])
    key_terms_block = (
        "Key terms that MUST be covered:\n"
        + "\n".join(f"  - {t}" for t in key_terms)
        + "\n"
    ) if key_terms else ""

    prompt = HEADING_INFER_PROMPT.format(
        subject=subject, author=author, key_terms_block=key_terms_block
    )

    _t0 = time.time()
    raw_response = llm.invoke(prompt).content
    event_log.llm("web_researcher/planner", "infer_headings", model, time.time() - _t0)
    parsed: dict | None = None
    error: str | None = None
    try:
        parsed = extract_json(raw_response)
    except (json.JSONDecodeError, ValueError) as e:
        error = f"JSON parse error: {e}"
        parsed = {"headings": []}

    headings = [
        Heading(id=h["id"], title=h["title"], description=h.get("description", ""))
        for h in parsed.get("headings", [])
    ]

    log.append(create_step(
        layer="web_researcher", node="planner",
        action="infer_headings",
        input_summary=f"subject='{subject}', author='{author}'",
        llm_prompt=prompt,
        llm_raw_response=raw_response,
        parsed_output=parsed,
        error=error,
        reasoning=f"LLM inferred {len(headings)} headings (fallback)",
    ))

    return headings, log
