"""WebResearcher — Step 1: determine topic headings.

Two modes:
  config  — headings are listed in book_config['web_research']['headings']
  infer   — headings are generated by an LLM given the subject / author

Output: list[Heading]
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field

from langchain_ollama import ChatOllama

from src.logger import create_step, extract_json


@dataclass
class Heading:
    id: str         # snake_case slug, e.g. "method_of_doubt"
    title: str      # human-readable, e.g. "Method of Doubt"
    description: str = ""  # optional context for search query generation


HEADING_INFER_PROMPT = """\
You are a knowledgeable research assistant.

Given the following subject, list the 6-10 most important themes, chapters, or conceptual
sections that a researcher would need to understand in order to fully grasp the content
and significance of this work.

Subject: {subject}
Author: {author}

For each heading provide:
- id: a snake_case slug
- title: the heading name (in English)
- description: one sentence explaining why this section is important

Respond ONLY with valid JSON:
{{
  "headings": [
    {{"id": "...", "title": "...", "description": "..."}}
  ]
}}
"""


def plan_headings(
    subject: str,
    author: str = "",
    book_config: dict | None = None,
    model: str = "llama3",
) -> tuple[list[Heading], list[dict]]:
    """Determine which headings to research.

    If book_config contains ['web_research']['headings'], those are used directly.
    Otherwise, an LLM infers the headings from the subject/author.

    Args:
        subject:     Full description of the subject (e.g. '方法序説 by デカルト').
        author:      Author name for the LLM prompt.
        book_config: Optional loaded book config dict.
        model:       Ollama model for inference mode.

    Returns:
        (list[Heading], thinking_log_entries)
    """
    log: list[dict] = []

    # ── Config-defined headings ───────────────────────────────────────────────
    if book_config:
        wr_config = book_config.get("web_research", {})
        raw_headings = wr_config.get("headings", [])
        if raw_headings:
            headings = [
                Heading(
                    id=h["id"],
                    title=h["title"],
                    description=h.get("description", ""),
                )
                for h in raw_headings
            ]
            log.append(create_step(
                layer="web_researcher", node="planner",
                action="use_config_headings",
                input_summary=f"{len(headings)} headings from book config",
                parsed_output={"headings": [h.__dict__ for h in headings]},
                reasoning="Using pre-defined headings from book config",
            ))
            return headings, log

    # ── LLM-inferred headings ─────────────────────────────────────────────────
    num_ctx = 16384
    llm = ChatOllama(model=model, temperature=0.2, num_ctx=num_ctx, format="json")
    prompt = HEADING_INFER_PROMPT.format(subject=subject, author=author)

    raw_response = llm.invoke(prompt).content
    parsed: dict | None = None
    error: str | None = None
    try:
        parsed = extract_json(raw_response)
    except (json.JSONDecodeError, ValueError) as e:
        error = f"JSON parse error: {e}"
        parsed = {"headings": []}

    headings = [
        Heading(id=h["id"], title=h["title"], description=h.get("description", ""))
        for h in parsed.get("headings", [])
    ]

    log.append(create_step(
        layer="web_researcher", node="planner",
        action="infer_headings",
        input_summary=f"subject='{subject}', author='{author}'",
        llm_prompt=prompt,
        llm_raw_response=raw_response,
        parsed_output=parsed,
        error=error,
        reasoning=f"LLM inferred {len(headings)} headings",
    ))

    return headings, log
